### ISSUE TITLE
[Suggestion] 移除隐私信息和缓存数据

### ISSUE THREAD

**Issue by LovelyCatHyt** [haogaulle/CSU-UnicomCampusNetwork-AutomaticLogin#1]
学号: [func/config.json](https://github.com/haogaulle/CSU-UnicomCampusNetwork-AutomaticLogin/blob/cd78185c8148ae8f49e4da60004530a9058c2b6b/func/config.json#L2)
缓存数据: [func/\_\_pycache\_\_](https://github.com/haogaulle/CSU-UnicomCampusNetwork-AutomaticLogin/tree/master/func/__pycache__)
实际上即使 push 新的 commit, 这些数据也会保存在 github 上, 只有删库(然后提交干净的版本)才可能会清除.
可以了解一下 .gitignore 的作用及用法.
配置文件可以只提交一个不含个人信息的样例, 能表达清楚文件格式即可.
最后, 感谢代码提供思路. 祝期末顺利 :)

**Comment by haogaulle** [comment]
感谢提交issue提醒！
问题现在已经解决，万分感谢！
祝期末顺利😉
